### ISSUE TITLE
High availability

### ISSUE THREAD

**Issue by leonardotorresaltez** [factorhouse/kpow-local#4]
Hello can i install kpow pods in Kubernetes with high availability active-active ? two or more pods ?

Regards, 
Leonardo

**Comment by d-t-w** [comment]
Hi @leonardotorresaltez. It is possible to run multiple Kpow pods in Kubernetesn for the same Kafka cluster, though we generally don't recommend that deployment style unless it's absolutely necessary. There are technical and licensing impacts.

Technical:

Kpow monitors each connected Kafka resource (cluster, schema, connect, ksqldb) once per minute. Running multiple instances of Kpow increases that load on each resource. For small clusters this is fairly negligible, but still not ideal.

Kpow stores data in the first configured cluster (if you are using a version of Kpow other than Community Edition), further installations of Kpow with the same Kafka cluster require some configuration of persistence-mode to run in an ephemeral way or to have different primary clusters.

Licensing:

Connecting two Kpow to one Kafka Cluster requires two cluster credits of your license.

If you would like any further info send an email to support@factorhouse.io.
