### ISSUE TITLE
Error: Manifest unknown 

### ISSUE THREAD

**Issue by ghost** [factorhouse/kpow-local#5]
<img width="563" alt="Screenshot 2023-09-14 at 2 14 45 PM" src="https://github.com/factorhouse/kpow-local/assets/144885848/18bb9a0b-f672-4281-ad0c-7780e3746282">

**Comment by d-t-w** [comment]
Thanks for the info, we needed to update the kpow version to 91.5.1.

I also added some details to the README about adding your license to local.env.
